[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.install]
cmds = [
  "npm install -g $(node -p \"require('./package.json').packageManager\")",
  "node $(npm root -g)/pnpm/bin/pnpm.cjs i --frozen-lockfile"
]

[phases.build]
cmds = [
  "node $(npm root -g)/pnpm/bin/pnpm.cjs run build"
]
